services:
  app:
    command: npm run start:debug
    ports:
      - "3000:3000"
      - "9229:9229" # Puerto de debug
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
